services:
  - type: web
    name: nepcrew
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT backend2pm.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - fromDatabase:
          name: nepcrewdb
          property: connectionString

