# Generated by Django 5.1.1 on 2026-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepcrewpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
