# Generated by Django 5.1.1 on 2026-04-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepcrewpage', '0002_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
